#!/bin/bash
# This file generates entire contents for FinalCrypt.scene
# rdj/scenes/FinalCrypt.bash > rdj/scenes/FinalCrypt.scene; java -jar GravitySimulator3D.jar FinalCrypt.scene
echo "################## General Settings ####################"
echo "#"
echo "Begin = General Settings"
echo "Verbosity = 1"
echo "SceneColor = BLACK"
#echo "SceneColor = WHITE"
echo "SceneId = FinalCrypt Scene"
echo "SceneTargetFrameRate = 0 # 0 = no delay, >0 = fixed targetframerate"
echo "SceneMotionRate = 100 # Range = 0-1000"
echo "SceneMotionFactor = 1"
echo "SceneGravityFactor = 1"
echo "StartsWithDisplays = False"
echo "StartsWithMotion = False"
echo "End = General Settings"
echo "#"
echo "################## Cam1 ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = cam1"
echo "Function = Camera"
echo "ZoomAngle = 31.0"
echo "LightType = 2"
echo "MeshFile = /rdj/resources/Shared/vcam.dae"
echo "#"
echo "# Celestial"
echo "#"
echo "CelestialRef = cam"
echo "#CelestialName = cam1"
echo "#CelestialMass = 10.0"
echo "#CelestialRadius = 0.0"
echo "#CelestialGravitational = False"
echo "#CelestialCollisional = False"
echo "#CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 2.0"
echo "RotEngPwrMassFactor = 2.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = 275.0"
echo "TranslateY = -50.0"
echo "TranslateZ = -970"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "AddNodeToScene = True"
echo "End = Object"

echo "#"
echo "################## Cam2 ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = cam2"
echo "Function = Camera"
echo "ZoomAngle = 58.16"
echo "LightType = 2"
echo "MeshFile = /rdj/resources/Shared/vcam.dae"
echo "#"
echo "# Celestial"
echo "#"
echo "CelestialRef = cam"
echo "#CelestialName = cam2"
echo "#CelestialMass = 10.0"
echo "#CelestialRadius = 0.0"
echo "#CelestialGravitational = False"
echo "#CelestialCollisional = False"
echo "#CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 2.0"
echo "RotEngPwrMassFactor = 2.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = -260.87"
echo "TranslateY = -50.0"
echo "TranslateZ = -914.59"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 45.28"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "AddNodeToScene = True"
echo "End = Object"

echo "#"
echo "################## Cam3 ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = cam3"
echo "Function = Camera"
echo "ZoomAngle = 58.16"
echo "LightType = 2"
echo "MeshFile = /rdj/resources/Shared/vcam.dae"
echo "#"
echo "# Celestial"
echo "#"
echo "CelestialRef = cam"
echo "#CelestialName = cam2"
echo "#CelestialMass = 10.0"
echo "#CelestialRadius = 0.0"
echo "#CelestialGravitational = False"
echo "#CelestialCollisional = False"
echo "#CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 2.0"
echo "RotEngPwrMassFactor = 2.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = -204.14"
echo "TranslateY = -48.069"
echo "TranslateZ = -327.80"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 65.14"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "AddNodeToScene = True"
echo "End = Object"

echo "#"
echo "################## Personal Cipher Encryption Description ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = cipherdesc"
echo "Function = Text"
echo "TextOrFile = Personal Cipher Encryption"
echo "FontName = Droid Sans"
echo "FontSize = 48"
echo "Color = GREY"
echo "# MeshNodeFilter = nodename"
echo "#"
echo "# Celestial"
echo "#"
echo "CelestialRef = dummy"
echo "#CelestialName = dummy"
echo "#CelestialMass = 1e12"
echo "#CelestialRadius = 5.0"
echo "#CelestialGravitational = False"
echo "#CelestialCollisional = False"
echo "#CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 0.5"
echo "RotEngPwrMassFactor = 2.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.35"
echo "ScaleY = 1.35"
echo "ScaleZ = 1.35"
echo "TranslateX = 55"
echo "TranslateY = -200"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "AddNodeToScene = True"
echo "End = Object"

echo "#"
echo "################## Cipher Text ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = cipherdesc"
echo "Function = Text"
echo "TextOrFile = Cipher"
echo "FontName = Droid Sans"
echo "FontSize = 32"
echo "Color = GREY"
echo "# MeshNodeFilter = nodename"
echo "#"
echo "# Celestial"
echo "#"
echo "CelestialRef = dummy"
echo "#CelestialName = dummy"
echo "#CelestialMass = 1e12"
echo "#CelestialRadius = 5.0"
echo "#CelestialGravitational = False"
echo "#CelestialCollisional = False"
echo "#CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 0.5"
echo "RotEngPwrMassFactor = 2.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = -200"
echo "TranslateY = -100"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "AddNodeToScene = True"
echo "End = Object"

echo "#"
echo "################## Data Text ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = datadesc"
echo "Function = Text"
echo "TextOrFile = Data"
echo "FontName = Droid Sans"
echo "FontSize = 32"
echo "Color = GREY"
echo "# MeshNodeFilter = nodename"
echo "#"
echo "# Celestial"
echo "#"
echo "CelestialRef = dummy"
echo "#CelestialName = dummy"
echo "#CelestialMass = 1e12"
echo "#CelestialRadius = 5.0"
echo "#CelestialGravitational = False"
echo "#CelestialCollisional = False"
echo "#CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 0.5"
echo "RotEngPwrMassFactor = 2.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = -200"
echo "TranslateY = 20"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "AddNodeToScene = True"
echo "End = Object"


declare -a col=("BLACK" "WHITE")
s=0
o=0
y=0
while [  ${y} -lt 1 ];
do
 x=0
 while [  ${x} -lt 128 ];
 do
  cr=$((RANDOM % 2))
  dr=$((RANDOM % 2))
  if [[ ${s} -eq 8 ]]; then let o=o+1; let s=1; fi
  echo "#"
  echo "################## Cipher$((${x}+${y})) ####################"
  echo "#"
  echo "Begin = Object"
  echo "Verbosity = 0"
  echo "Quantity = 1"
  echo "Lifetime = -1 # mSec"
  echo "OnMenu = False"
  echo "Load = True"
  echo "Type = Node"
  echo "Name = cipher$((${x}+${y}))"
  echo "Function = Sphere"
#  echo "Divisions = ${cr} * 32"
  echo "Divisions = 64"
  echo "CullFace = BACK # BACK / FRONT / NONE"
  echo "DrawMode = FILL # LINE / FILL"
#  echo "Color = ${col[${cr}]}"
  echo "Color = GREY"
  echo "MapType = DiffuseMap # DiffuseColor / DiffuseMap / SelfIlluminationMap / BumpMap"
  echo "ImageFile = /rdj/resources/FinalCryptScene/bitnum.jpg"
  echo "Width = 1.0"
  echo "Height = 1.0"
  echo "Depth = 1.0"
  echo ""
  echo "DropTrail = False"
  echo "TrailLength = 50"
  echo "TrailColor = INDIANRED"
  echo "TrailCullFace = BACK # BACK / FRONT / NONE"
  echo "TrailDrawMode = FILL # LINE / FILL"
  echo "DropTrailInterval = 10000 # mSec"
  echo "TrailRadiusPercentage = 10.0"
  echo "TrailOpacity = 1.0 # 0.0 - 1.0 (Doesn't work yet, keep on 1)"
  echo "#"
  echo "# Celestial"
  echo "#"
  echo "#CelestialRef = bit"
  echo "CelestialName = cipher$((${x}+${y}))"
  echo "CelestialMass = 1"
  echo "CelestialRadius = 50.5"
  echo "CelestialGravitational = False"
  echo "CelestialCollisional = False"
  echo "CelestialPolarity = 1"
  echo "#"
  echo "# Motion"
  echo "#"
  echo "StartingWithMotion = True"
  echo "MotionStateChangeble = False"
  echo "MainEngPwrMassFactor = 10.0"
  echo "TransEngPwrMassFactor = 1.0"
  echo "RotEngPwrMassFactor = 1.0"
  echo "#"
  echo "# Coordinal"
  echo "#"
  echo "ScaleX = 1.0"
  echo "ScaleY = 1.0"
  echo "ScaleZ = 1.0"
  echo "TranslateX = ${o} + ${x}.0 * 100"
  echo "TranslateY = (${y}.0 * 100) - 100"
  echo "TranslateZ = 0.0"
  echo "TranslateXMotion = 0.0"
  echo "TranslateYMotion = 0.0"
  echo "TranslateZMotion = 0.0"
  echo "RotationX = ${cr} * 180.0"
  echo "RotationY = 0.0"
  echo "RotationZ = 0.0"
  echo "RotationXMotion = 0.0"
  echo "RotationYMotion = 0.0"
  echo "RotationZMotion = 0.0"
  echo "#"
  echo "# Rotation Pivot Points"
  echo "#"
  echo "# RotationXX = 0.0"
  echo "# RotationXY = 0.0"
  echo "# RotationXZ = 0.0"
  echo "# RotationYX = 0.0"
  echo "# RotationYY = 0.0"
  echo "# RotationYZ = 0.0"
  echo "# RotationZX = 0.0"
  echo "# RotationZY = 0.0"
  echo "# RotationZZ = 0.0"
  echo "#"
  echo "# State"
  echo "#"
  echo "Cached = False"
  echo "#"
  echo "SetTransitions = True"
  echo "BackupCoordinalState = True"
  echo "AddNodeToList = True"
  echo "SetNodeVisible = True"
  echo "AddNodeToScene = True"
  echo "End = Object"
  
  
  
  if [ ${cr} -eq 1 ]
  then
echo "#"
echo "################## Text$((${x}+${y})) ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = False"
echo "Load = True"
echo "Type = Node"
echo "Name = text$((${x}+${y}))"
echo "Function = Text"
echo "TextOrFile = Invert"
echo "FontName = Droid Sans"
echo "FontSize = 24"
echo "Color = GREY"
echo "# MeshNodeFilter = nodename"
echo "#"
echo "# Celestial"
echo "#"
echo "CelestialRef = dummy"
echo "#CelestialName = dummy"
echo "#CelestialMass = 1e12"
echo "#CelestialRadius = 5.0"
echo "#CelestialGravitational = False"
echo "#CelestialCollisional = False"
echo "#CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 0.5"
echo "RotEngPwrMassFactor = 2.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = (${o} + ${x}.0 * 100) - 25"
echo "TranslateY = (${y}.0 * 100) - 35"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "AddNodeToScene = True"
echo "End = Object"

  echo "#"
  echo "################## CFrame$((${x}+${y})) ####################"
  echo "#"
  echo "Begin = Object"
  echo "Verbosity = 0"
  echo "Quantity = 1"
  echo "Lifetime = -1 # mSec"
  echo "OnMenu = False"
  echo "Load = False"
  echo "Type = Node"
  echo "Name = cframe$((${x}+${y}))"
  echo "Function = Sphere"
#  echo "Divisions = ${cr} * 32"
  echo "Divisions = 32"
  echo "CullFace = BACK # BACK / FRONT / NONE"
  echo "DrawMode = LINE # LINE / FILL"
#  echo "Color = ${col[${cr}]}"
  echo "Color = GREY"
  echo "MapType = DiffuseMap # DiffuseColor / DiffuseMap / SelfIlluminationMap / BumpMap"
#  echo "ImageFile = /rdj/resources/FinalCryptScene/bitnum.jpg"
  echo "Width = 1.0"
  echo "Height = 1.0"
  echo "Depth = 1.0"
  echo ""
  echo "DropTrail = False"
  echo "TrailLength = 50"
  echo "TrailColor = INDIANRED"
  echo "TrailCullFace = BACK # BACK / FRONT / NONE"
  echo "TrailDrawMode = FILL # LINE / FILL"
  echo "DropTrailInterval = 10000 # mSec"
  echo "TrailRadiusPercentage = 10.0"
  echo "TrailOpacity = 1.0 # 0.0 - 1.0 (Doesn't work yet, keep on 1)"
  echo "#"
  echo "# Celestial"
  echo "#"
  echo "#CelestialRef = bit"
  echo "CelestialName = cipher$((${x}+${y}))"
  echo "CelestialMass = 1"
  echo "CelestialRadius = 50.5"
  echo "CelestialGravitational = False"
  echo "CelestialCollisional = False"
  echo "CelestialPolarity = 1"
  echo "#"
  echo "# Motion"
  echo "#"
  echo "StartingWithMotion = True"
  echo "MotionStateChangeble = False"
  echo "MainEngPwrMassFactor = 10.0"
  echo "TransEngPwrMassFactor = 1.0"
  echo "RotEngPwrMassFactor = 1.0"
  echo "#"
  echo "# Coordinal"
  echo "#"
  echo "ScaleX = 1.1"
  echo "ScaleY = 1.1"
  echo "ScaleZ = 1.1"
  echo "TranslateX = ${o} + ${x}.0 * 100"
  echo "TranslateY = ${y}.0 * 100 + 25"
  echo "TranslateZ = 0.0"
  echo "TranslateXMotion = 0.0"
  echo "TranslateYMotion = 0.0"
  echo "TranslateZMotion = 0.0"
  echo "RotationX = 180.0"
  echo "RotationY = 0.0"
  echo "RotationZ = 0.0"
  echo "RotationXMotion = ${cr} * 0.0"
  echo "RotationYMotion = -3.0"
  echo "RotationZMotion = 0.0"
  echo "#"
  echo "# Rotation Pivot Points"
  echo "#"
  echo "# RotationXX = 0.0"
  echo "# RotationXY = 0.0"
  echo "# RotationXZ = 0.0"
  echo "# RotationYX = 0.0"
  echo "# RotationYY = 0.0"
  echo "# RotationYZ = 0.0"
  echo "# RotationZX = 0.0"
  echo "# RotationZY = 0.0"
  echo "# RotationZZ = 0.0"
  echo "#"
  echo "# State"
  echo "#"
  echo "Cached = False"
  echo "#"
  echo "SetTransitions = True"
  echo "BackupCoordinalState = True"
  echo "AddNodeToList = True"
  echo "SetNodeVisible = True"
  echo "AddNodeToScene = True"
  echo "End = Object"
  fi
  echo "#"
  echo "################## Data$((${x}+${y})) ####################"
  echo "#"
  echo "Begin = Object"
  echo "Verbosity = 0"
  echo "Quantity = 1"
  echo "Lifetime = -1 # mSec"
  echo "OnMenu = False"
  echo "Load = True"
  echo "Type = Node"
  echo "Name = data$((${x}+${y}))"
  echo "Function = Sphere"
  echo "Divisions = 64"
  echo "CullFace = BACK # BACK / FRONT / NONE"
  echo "DrawMode = FILL # LINE / FILL"
  echo "Color = BLACK"
  echo "MapType = DiffuseMap # DiffuseColor / DiffuseMap / SelfIlluminationMap / BumpMap"
  echo "ImageFile = /rdj/resources/FinalCryptScene/bitnum.jpg"
  echo ""
  echo "DropTrail = False"
  echo "TrailLength = 50"
  echo "TrailColor = INDIANRED"
  echo "TrailCullFace = BACK # BACK / FRONT / NONE"
  echo "TrailDrawMode = FILL # LINE / FILL"
  echo "DropTrailInterval = 10000 # mSec"
  echo "TrailRadiusPercentage = 10.0"
  echo "TrailOpacity = 1.0 # 0.0 - 1.0 (Doesn't work yet, keep on 1)"
  echo "#"
  echo "# Celestial"
  echo "#"
  echo "#CelestialRef = bit"
  echo "CelestialName = data$((${x}+${y}))"
  echo "CelestialMass = 1"
  echo "CelestialRadius = 50.0"
  echo "#CelestialGravitational = False"
  echo "CelestialCollisional = False"
  echo "CelestialPolarity = 1"
  echo "#"
  echo "# Motion"
  echo "#"
  echo "StartingWithMotion = False"
  echo "MotionStateChangeble = True"
  echo "MainEngPwrMassFactor = 10.0"
  echo "TransEngPwrMassFactor = 1.0"
  echo "RotEngPwrMassFactor = 1.0"
  echo "#"
  echo "# Coordinal"
  echo "#"
  echo "ScaleX = 1.0"
  echo "ScaleY = 1.0"
  echo "ScaleZ = 1.0"
  echo "TranslateX = ${o} + ${x}.0 * 100"
  echo "TranslateY = (${y} + 0.0) * 100 + 25"
  echo "TranslateZ = 0.0"
  echo "TranslateXMotion = 0.0"
  echo "TranslateYMotion = 0.0"
  echo "TranslateZMotion = 0.0"
  echo "RotationX = ${dr} * 180.0"
  echo "RotationY = 0.0"
  echo "RotationZ = 0.0"
  echo "RotationXMotion = ${cr} * 100.0"
  echo "RotationYMotion = 0.0"
  echo "RotationZMotion = 0.0"
  echo "#"
  echo "# Rotation Pivot Points"
  echo "#"
  echo "# RotationXX = 0.0"
  echo "# RotationXY = 0.0"
  echo "# RotationXZ = 0.0"
  echo "# RotationYX = 0.0"
  echo "# RotationYY = 0.0"
  echo "# RotationYZ = 0.0"
  echo "# RotationZX = 0.0"
  echo "# RotationZY = 0.0"
  echo "# RotationZZ = 0.0"
  echo "#"
  echo "# State"
  echo "#"
  echo "Cached = False"
  echo "#"
  echo "SetTransitions = True"
  echo "BackupCoordinalState = True"
  echo "AddNodeToList = True"
  echo "SetNodeVisible = True"
  echo "AddNodeToScene = True"
  echo "End = Object"
echo "#"
echo "################## Text ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = False"
echo "Load = True"
echo "Type = Node"
echo "Name = cipher"
echo "Function = Text"
echo "TextOrFile = ${x}"
echo "FontName = Droid Sans"
echo "FontSize = 48"
echo "Color = GREY"
echo "# MeshNodeFilter = nodename"
echo "#"
echo "# Celestial"
echo "#"
echo "CelestialRef = dummy"
echo "#CelestialName = dummy"
echo "#CelestialMass = 1e12"
echo "#CelestialRadius = 5.0"
echo "#CelestialGravitational = False"
echo "#CelestialCollisional = False"
echo "#CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 0.5"
echo "RotEngPwrMassFactor = 2.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = (${o} + ${x}.0 * 100) - 20"
echo "TranslateY = (${y}.0 * 100) + 120"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "AddNodeToScene = True"
echo "End = Object"
  
  
  let s=s+1
  let x=x+1
 done
 let y=y+1
done

echo "#"
echo "################## upwall ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "Group = Begin"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = upwall "
echo "Function = Box"
echo "CullFace = BACK # BACK / FRONT / NONE"
echo "DrawMode = FILL # LINE / FILL"
echo "Color = BLACK"
echo "MapType = DiffuseMap # DiffuseColor / DiffuseMap / SelfIlluminationMap / BumpMap"
echo "ImageFile = /rdj/resources/Shared/wall-up-black-lowres.jpg"
echo "ImageFile = /rdj/resources/Shared/cirquit-board-dark-tiles.jpg"
echo "Width = 1000000.0"
echo "Height = 1000000.0"
echo "Depth = 1.0"
echo "#"
echo "# Celestial"
echo "#"
echo "#CelestialRef = wall"
echo "CelestialName = wall"
echo "CelestialMass = 1000.0"
echo "CelestialRadius = 1000.0"
echo "CelestialGravitational = False"
echo "CelestialCollisional = False"
echo "CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 1.0"
echo "RotEngPwrMassFactor = 1.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = 0.0"
echo "TranslateY = -500000.0"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 90.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "#BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "#AddNodeToScene = True"
echo "End = Object"
echo "#"
echo "################## backWall ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = backWall "
echo "Function = Box"
echo "CullFace = BACK # BACK / FRONT / NONE"
echo "DrawMode = FILL # LINE / FILL"
echo "Color = BLACK"
echo "MapType = DiffuseMap # DiffuseColor / DiffuseMap / SelfIlluminationMap / BumpMap"
echo "ImageFile = /rdj/resources/Shared/wall-back-black-lowres.jpg"
echo "ImageFile = /rdj/resources/Shared/cirquit-board-dark-tiles.jpg"
echo "Width = 1000000.0"
echo "Height = 1000000.0"
echo "Depth = 1.0"
echo "#"
echo "# Celestial"
echo "#"
echo "#CelestialRef = wall"
echo "CelestialName = wall"
echo "CelestialMass = 1000.0"
echo "CelestialRadius = 1000.0"
echo "CelestialGravitational = False"
echo "CelestialCollisional = False"
echo "CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 1.0"
echo "RotEngPwrMassFactor = 1.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = 0.0"
echo "TranslateY = 0.0"
echo "TranslateZ = -500000.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "#BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "#AddNodeToScene = True"
echo "End = Object"
echo "#"
echo "################## frontwall ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = frontwall "
echo "Function = Box"
echo "CullFace = BACK # BACK / FRONT / NONE"
echo "DrawMode = FILL # LINE / FILL"
echo "Color = BLACK"
echo "MapType = DiffuseMap # DiffuseColor / DiffuseMap / SelfIlluminationMap / BumpMap"
#echo "ImageFile = /rdj/resources/Shared/wall-front-black-lowres.jpg"
echo "ImageFile = /rdj/resources/Shared/cirquit-board-dark-tiles.jpg"
echo "Width = 1000000.0"
echo "Height = 1000000.0"
echo "Depth = 1.0"
echo "#"
echo "# Celestial"
echo "#"
echo "#CelestialRef = wall"
echo "CelestialName = wall"
echo "CelestialMass = 1000.0"
echo "CelestialRadius = 1000.0"
echo "CelestialGravitational = False"
echo "CelestialCollisional = False"
echo "CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 1.0"
echo "RotEngPwrMassFactor = 1.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = 0.0"
echo "TranslateY = 0.0"
echo "TranslateZ = 500000.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "#BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "#AddNodeToScene = True"
echo "End = Object"
echo "#"
echo "################## leftwall ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = leftwall "
echo "Function = Box"
echo "CullFace = BACK # BACK / FRONT / NONE"
echo "DrawMode = FILL # LINE / FILL"
echo "Color = BLACK"
echo "MapType = DiffuseMap # DiffuseColor / DiffuseMap / SelfIlluminationMap / BumpMap"
echo "ImageFile = /rdj/resources/Shared/wall-left-black-lowres.jpg"
echo "ImageFile = /rdj/resources/Shared/cirquit-board-dark-tiles.jpg"
echo "Width = 1000000.0"
echo "Height = 1000000.0"
echo "Depth = 1.0"
echo "#"
echo "# Celestial"
echo "#"
echo "#CelestialRef = wall"
echo "CelestialName = wall"
echo "CelestialMass = 1000.0"
echo "CelestialRadius = 1000.0"
echo "CelestialGravitational = False"
echo "CelestialCollisional = False"
echo "CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 1.0"
echo "RotEngPwrMassFactor = 1.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = -500000.0"
echo "TranslateY = 0.0"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 90.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "#BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "#AddNodeToScene = True"
echo "End = Object"
echo "#"
echo "################## rightwall ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = rightwall "
echo "Function = Box"
echo "CullFace = BACK # BACK / FRONT / NONE"
echo "DrawMode = FILL # LINE / FILL"
echo "Color = BLACK"
echo "MapType = DiffuseMap # DiffuseColor / DiffuseMap / SelfIlluminationMap / BumpMap"
echo "ImageFile = /rdj/resources/Shared/wall-right-black-lowres.jpg"
echo "ImageFile = /rdj/resources/Shared/cirquit-board-dark-tiles.jpg"
echo "Width = 1000000.0"
echo "Height = 1000000.0"
echo "Depth = 1.0"
echo "#"
echo "# Celestial"
echo "#"
echo "#CelestialRef = wall"
echo "CelestialName = wall"
echo "CelestialMass = 1000.0"
echo "CelestialRadius = 1000.0"
echo "CelestialGravitational = False"
echo "CelestialCollisional = False"
echo "CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 1.0"
echo "RotEngPwrMassFactor = 1.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = 500000.0"
echo "TranslateY = 0.0"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = -90.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "#BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "#AddNodeToScene = True"
echo "End = Object"
echo "#"
echo "################## downwall ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = downwall "
echo "Function = Box"
echo "CullFace = BACK # BACK / FRONT / NONE"
echo "DrawMode = FILL # LINE / FILL"
echo "Color = BLACK"
echo "MapType = DiffuseMap # DiffuseColor / DiffuseMap / SelfIlluminationMap / BumpMap"
echo "ImageFile = /rdj/resources/Shared/wall-down-black-lowres.jpg"
echo "ImageFile = /rdj/resources/Shared/cirquit-board-dark-tiles.jpg"
echo "Width = 1000000.0"
echo "Height = 1000000.0"
echo "Depth = 1.0"
echo "#"
echo "# Celestial"
echo "#"
echo "#CelestialRef = wall"
echo "CelestialName = wall"
echo "CelestialMass = 1000.0"
echo "CelestialRadius = 1000.0"
echo "CelestialGravitational = False"
echo "CelestialCollisional = False"
echo "CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 1.0"
echo "RotEngPwrMassFactor = 1.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = 0.0"
echo "TranslateY = 500000.0"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 90.0"
echo "RotationY = 180.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "#BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "#AddNodeToScene = True"
echo "End = Object"
echo "#"
echo "################## Dummy ####################"
echo "#"
echo "Begin = Object"
echo "Verbosity = 0"
echo "Quantity = 1"
echo "Lifetime = -1 # mSec"
echo "OnMenu = True"
echo "Load = True"
echo "Type = Node"
echo "Name = wall "
echo "Function = Dummy"
echo "#"
echo "# Celestial"
echo "#"
echo "CelestialRef = dummy"
echo "#CelestialName = dummy"
echo "#CelestialMass = 1.0"
echo "#CelestialRadius = 1.0"
echo "#CelestialGravitational = False"
echo "#CelestialCollisional = False"
echo "#CelestialPolarity = 0"
echo "#"
echo "# Motion"
echo "#"
echo "StartingWithMotion = True"
echo "MotionStateChangeble = False"
echo "MainEngPwrMassFactor = 10.0"
echo "TransEngPwrMassFactor = 1.0"
echo "RotEngPwrMassFactor = 1.0"
echo "#"
echo "# Coordinal"
echo "#"
echo "ScaleX = 1.0"
echo "ScaleY = 1.0"
echo "ScaleZ = 1.0"
echo "TranslateX = 0.0"
echo "TranslateY = 0.0"
echo "TranslateZ = 0.0"
echo "TranslateXMotion = 0.0"
echo "TranslateYMotion = 0.0"
echo "TranslateZMotion = 0.0"
echo "RotationX = 0.0"
echo "RotationY = 0.0"
echo "RotationZ = 0.0"
echo "RotationXMotion = 0.0"
echo "RotationYMotion = 0.0"
echo "RotationZMotion = 0.0"
echo "#"
echo "# Rotation Pivot Points"
echo "#"
echo "# RotationXX = 0.0"
echo "# RotationXY = 0.0"
echo "# RotationXZ = 0.0"
echo "# RotationYX = 0.0"
echo "# RotationYY = 0.0"
echo "# RotationYZ = 0.0"
echo "# RotationZX = 0.0"
echo "# RotationZY = 0.0"
echo "# RotationZZ = 0.0"
echo "#"
echo "# State"
echo "#"
echo "Cached = True"
echo "#"
echo "SetTransitions = True"
echo "BackupCoordinalState = True"
echo "AddNodeToList = True"
echo "SetNodeVisible = True"
echo "AddNodeToScene = True"
echo "Group = End"
echo "End = Object"
echo "#"
echo ""
